/*Template generated by WebStorm on Sunday (7/7/24), 12:14 PM.
* Author: kramstyles
* Filename: index.jsx
*/

import "./index.css";

const WhatsappChannel = () => {
    return (
        <div className="container text-center mt-4">
            <a href="https://whatsapp.com/channel/0029VaGnbXuCsU9Si7zguy0S" className="btn btn-whatsapp btn-lg">
                Follow the Pacesetter Frontier Magazine Channel on WhatsApp for News Updates.  Click to Join.
            </a>
        </div>
    );
};

export default WhatsappChannel;
