/*Template generated by WebStorm on Friday (9/8/23), 3:10 AM.
* Author: kramstyles
* Filename: SideBar.jsx
*/

import {ArticleTitle, SocialPills, SideBarRecentSlider, Adverts} from "../assets/components";
import {socials} from "../assets/data";

const SideBar = () => {
    return (
        <div>
            <ArticleTitle title="Advertise with us" class_="fs-5" width={65} />
            <Adverts index={0} hideLabel={true}/>
            <ArticleTitle title="Stay Connected" class_="fs-5 mt-5" width={50} />
            <div className="my-4">
                {socials.map((item, index) => (
                    <SocialPills name={item.word} icon={item.icon} link={item.link} _class={item.pill_class} key={index} number={item.limit}/>
                ))}
            </div>
            <ArticleTitle title="Recent News" width={50} class_="fs-5 mt-5" />
            <SideBarRecentSlider/>
        </div>
    );
};

export default SideBar;
