/*Template generated by WebStorm on Tuesday (7/18/23), 1:30 AM.
 * Author: kramstyles
 * Filename: Preloader.jsx
 */

import PropTypes from "prop-types";

import "./style.css";
const Preloader = ({fixed}) => {
  return (
    <div className={`my-preloader d-none ${fixed && "position-fixed"}`}>
      <div className="loader">
        <div className="loader-box">
          <div className="loader-box">
            <div className="loader-box">
              <div className="loader-box"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

Preloader.propTypes = {
  fixed: PropTypes.bool
}

export default Preloader;
