/*Template generated by WebStorm on Saturday (7/8/23), 3:34 PM.
 * Author: kramstyles
 * Filename: Top.jsx
 */
import { socials } from "../../data";

const Top = () => {
  // Generate and use date in this format 09 Jul, 2023 (Day I wrote this line)
  const currentDay = new Date();

  const day = currentDay.getDate().toString().padStart(2, "0");
  const month = currentDay.toLocaleString("default", { month: "short" });
  const year = currentDay.getFullYear();

  return (
    <div className="top-bar">
      <div className="container h-100">
        <div className="row h-100">
          <div className="col-xl-9 col-sm-2 col-md-6"></div>
          <div className="col-xl-3 col-sm-10 col-md-6 d-flex align-items-center h-100 top-icons">
            {socials.map((item) => (
                <a
                    href={item.link}
                    rel="noreferrer"
                    className="text-white p-1 px-2"
                    target="_blank"
                    key={item.name}
                    title={item.name}
                >{item.icon}</a>
            ))}

            <div className="top-divider mx-3" />
            <div className="row text-white align-items-center ms-2 rale fw-bold hide-on-sm">
              <div className="col-md-6">
                <h3 className="m-0">{day}</h3>
              </div>
              <div className="col-md-6 ps-1 d-flex row">
                <span className="ps-1 fs-11 text-capitalize">{month}</span>
                <span className="ps-1 fs-11">{year}</span>
              </div>
            </div>
            <div className="row hide-on-lg push-end">
              <div className="col-12 d-flex align-items-center text-white fw-bold">
                <span className="ps-1 fs-11 text-capitalize">{month} - </span>
                <h3 className="m-0">{day}</h3>
                <span className="ps-1 fs-12"> - {year}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Top;
