/*Template generated by WebStorm on Saturday (6/1/24), 2:55 PM.
 * Author: kramstyles
 * Filename: RemoveLater.jsx
 */
"use client"
import { useState } from "react";

function RemoveLater() {
  const [name, setName] = useState("Mary");
  const [age, setAge] = useState(16);
  const [license, setLicense] = useState("A123456");

  if (age < 16) {
    return (
      <div>
        Name:{" "}
        <input
          value={name}
          onChange={(e) => {
            setName(e.target.value);
          }}
        />
        <br />
        Age:{" "}
        <input
          value={age}
          type="number"
          onChange={(e) => {
            setAge(+e.target.value);
          }}
        />
      </div>
    );
  }

  return (
    <div>
      Name:{" "}
      <input
        value={name}
        onChange={(e) => {
          setName(e.target.value);
        }}
      />
      <br />
      Age:{" "}
      <input
        value={age}
        type="number"
        onChange={(e) => {
          setAge(+e.target.value);
        }}
      />
      <br />
      Driver License:{" "}
      <input
        value={license}
        onChange={(e) => {
          setLicense(e.target.value);
        }}
      />
    </div>
  );
}

export default RemoveLater;
