/*Template generated by WebStorm on Sunday (6/30/24), 11:47 AM.
* Author: kramstyles
* Filename: BusinessEconomy.jsx
*/

import {Common} from "../assets/components";

const BusinessEconomy = () => {
    return (
        <>
            <Common name="Business/Economy" start={0}/>
        </>
    );
};

export default BusinessEconomy;
