/*Template generated by WebStorm on Sunday (6/30/24), 11:45 AM.
* Author: kramstyles
* Filename: Education.jsx
*/

import {Common} from "../assets/components";

const Education = () => {
    return (
        <>
            <Common name="Education" start={0}/>
        </>
    );
};

export default Education;
