/*Template generated by WebStorm on Sunday (6/30/24), 11:19 AM.
* Author: kramstyles
* Filename: Entertainment.jsx
*/

import {Common} from "../assets/components";

const Entertainment = () => {
    return (
        <>
            <Common name="Entertainment" start={0}/>
        </>
    );
};

export default Entertainment;
