/*Template generated by WebStorm on Sunday (6/30/24), 11:19 AM.
* Author: kramstyles
* Filename: Fashion.jsx
*/
import { Common } from "../assets/components";

const Fashion = () => {
    return <Common name="Fashion" start={0} />
};

export default Fashion;
