/*Template generated by WebStorm on Sunday (6/30/24), 11:19 AM.
* Author: kramstyles
* Filename: Health.jsx
*/

import {Common} from "../assets/components";

const Health = () => {
    return (
        <>
            <Common name="Health" start={0}/>
        </>
    );
};

export default Health;
