/*Template generated by WebStorm on Sunday (6/30/24), 11:52 AM.
* Author: kramstyles
* Filename: Interviews.jsx
*/

import {Common} from "../assets/components";

const Interviews = () => {
    return (
        <>
            <Common name="Interviews" start={0}/>
        </>
    );
};

export default Interviews;
