/*Template generated by WebStorm on Sunday (6/30/24), 11:52 AM.
* Author: kramstyles
* Filename: Lifestyle.jsx
*/

import {Common} from "../assets/components";

const Lifestyle = () => {
    return (
        <>
            <Common name="Lifestyle" start={0}/>
        </>
    );
};

export default Lifestyle;
