/*Template generated by WebStorm on Saturday (7/22/23), 3:31 AM.
* Author: kramstyles
* Filename: News.jsx
*/
import { Common } from "../assets/components";

const News = () => {
    return <Common name="News" start={0} />
};

export default News;
