/*Template generated by WebStorm on Sunday (6/30/24), 12:19 PM.
* Author: kramstyles
* Filename: Novella.jsx
*/
import { Common } from "../assets/components";

const Novella = () => {
    return <Common name="Novella" start={0} />
};

export default Novella;
