/*Template generated by WebStorm on Sunday (7/23/23), 2:19 AM.
* Author: kramstyles
* Filename: Opinion.jsx
*/

import {Common} from "../assets/components";

const Opinion = () => {
    return (
        <>
            <Common name="Opinion" start={0}/>
        </>
    );
};

export default Opinion;
