/*Template generated by WebStorm on Sunday (7/23/23), 2:19 AM.
* Author: kramstyles
* Filename: Politics.jsx
*/

import {Common} from "../assets/components";

const Politics = () => {
    return (
        <>
            <Common name="Politics" start={0}/>
        </>
    );
};

export default Politics;
