/*Template generated by WebStorm on Sunday (6/30/24), 11:40 AM.
* Author: kramstyles
* Filename: PressRelease.jsx
*/

import {Common} from "../assets/components";

const PressRelease = () => {
    return (
        <>
            <Common name="Press Release" start={0}/>
        </>
    );
};

export default PressRelease;
