/*Template generated by WebStorm on Sunday (6/30/24), 2:19 AM.
* Author: kramstyles
* Filename: Religion.jsx
*/

import {Common} from "../assets/components";

const Religion = () => {
    return (
        <>
            <Common name="Religion" start={0}/>
        </>
    );
};

export default Religion;
