/*Template generated by WebStorm on Thursday (8/3/23), 9:43 PM.
 * Author: kramstyles
 * Filename: SideBar.jsx
 */

import { SideMain } from "../assets/components";

const SideBar = () => {
  return <SideMain />;
};

export default SideBar;
