/*Template generated by WebStorm on Sunday (6/30/24), 12:19 AM.
* Author: kramstyles
* Filename: Sports.jsx
*/

import {Common} from "../assets/components";

const Sports = () => {
    return (
        <>
            <Common name="Sports" start={0}/>
        </>
    );
};

export default Sports;
