/*Template generated by WebStorm on Sunday (6/30/24), 11:47 AM.
* Author: kramstyles
* Filename: Technology.jsx
*/

import {Common} from "../assets/components";

const Technology = () => {
    return (
        <>
            <Common name="Technology" start={0}/>
        </>
    );
};

export default Technology;
