/*Template generated by WebStorm on Sunday (8/20/23), 9:54 PM.
 * Author: kramstyles
 * Filename: Disclaimer.jsx
 */

import { CgPen } from "react-icons/cg";
import PropTypes from "prop-types";

const Disclaimer = ({ category }) => {
  // Setup Disclaimer options
  const OpinionDisclaimer = `
    Author's opinion above and comments expressed below by readers do not reflect the 
    opinions of <b>Pacesetter Frontier Magazine</b> or any employee thereof.`;
  const OtherDisclaimer = `
    Comments expressed below by readers do not reflect the opinions of 
    <b>Pacesetter Frontier Magazine</b> or any employee thereof.
  `;
  // Get category id and check if it's an opinion.
  const categoryID = category[0];
  let disclaimerComment = OtherDisclaimer;
  if (categoryID === 1) disclaimerComment = OpinionDisclaimer;
  return (
    <>
      <div className="container text-center my-5">
        <h4 className="text-danger mb-3">
          <b>Support Pacesetter Frontier Magazine</b>
        </h4>
        <p>It takes a lot to get credible, true and reliable stories.</p>
        <p>
          As a privately owned media outfit, we believe in setting the pace and
          leaving strides in time.
        </p>
        <p>
          If you like what we do, you can donate a token to us{" "}
          <a
            className="fw-bold text-danger text-decoration-none"
            href="https://paystack.com/pay/the_pacesetter_frontier_donate"
            rel="noreferrer"
            target="_blank"
          >
            here
          </a>
          . Your support will ensure that the right news is put out there at all
          times, reaching an unlimited number of persons at no cost to them.
        </p>
        <p>
          <a
            href="https://paystack.com/pay/the_pacesetter_frontier_donate"
            rel="noreferrer"
            target="_blank"
            className="btn btn-outline-danger p-3 px-5 rounded fw-bold"
          >
            Donate!
          </a>
        </p>
      </div>
      <div className="container rounded bg-disclaimer my-4 p-4">
        <h4 className="poppins fw-bold mb-3">
          Disclaimer <CgPen className="fs-5" />
        </h4>
        <p
            className="fs-14"
            dangerouslySetInnerHTML={{ __html: disclaimerComment }}
        />
      </div>
    </>
  );
};

Disclaimer.propTypes = {
  category: PropTypes.array.isRequired,
};

export default Disclaimer;
